import { Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../../prisma/prisma.service';
import { IConversationRepository } from '../interfaces';
import { Conversation, Message } from '../../conversation.types';
import { MessageRole } from '@prisma/client';

@Injectable()
export class PrismaConversationRepository implements IConversationRepository {
  constructor(private readonly prisma: PrismaService) {}

  async startConversation(workspaceId: string, metadata?: Record<string, any>): Promise<Conversation> {
    const conv = await this.prisma.conversation.create({
      data: {
        workspaceId,
        metadata: metadata || {},
      },
    });

    return this.mapToDomain(conv);
  }

  async getConversation(id: string): Promise<Conversation | null> {
    const conv = await this.prisma.conversation.findUnique({
      where: { id },
    });
    return conv ? this.mapToDomain(conv) : null;
  }

  async appendMessage(conversationId: string, runId: string | undefined, message: Message): Promise<Message> {
    const msg = await this.prisma.message.create({
      data: {
        id: message.id,
        conversationId,
        runId,
        role: message.role as MessageRole,
        metadata: message.metadata || {},
        parts: {
          create: message.parts.map((p) => ({
            id: p.id,
            type: p.type,
            status: p.status,
            order: p.order,
            content: p.content,
            metadata: p.metadata || {},
            toolCallId: p.toolCallId,
            createdAt: new Date(p.createdAt),
          })),
        },
      },
      include: { parts: true },
    });

    await this.prisma.conversation.update({
      where: { id: conversationId },
      data: { 
        version: { increment: 1 },
        lastMessageAt: msg.createdAt,
      },
    });

    return this.mapMessageToDomain(msg);
  }

  async getMessages(conversationId: string): Promise<Message[]> {
    const msgs = await this.prisma.message.findMany({
      where: { conversationId },
      include: { parts: { orderBy: { order: 'asc' } } },
      orderBy: { createdAt: 'asc' },
    });

    return msgs.map((msg) => this.mapMessageToDomain(msg));
  }

  private mapMessageToDomain(prismaModel: any): Message {
    return {
      id: prismaModel.id,
      role: prismaModel.role as any,
      createdAt: prismaModel.createdAt.getTime(),
      metadata: prismaModel.metadata,
      parts: (prismaModel.parts || []).map((p: any) => ({
        id: p.id,
        type: p.type,
        status: p.status,
        order: p.order,
        content: p.content,
        metadata: p.metadata,
        toolCallId: p.toolCallId,
        createdAt: p.createdAt.getTime(),
      })),
    };
  }

  private mapToDomain(prismaModel: any): Conversation {
    return {
      id: prismaModel.id,
      title: prismaModel.title ?? 'Untitled Conversation',
      summary: prismaModel.summary,
      isAutoGenerated: prismaModel.isAutoGenerated,
      createdAt: prismaModel.createdAt.getTime(),
      updatedAt: prismaModel.updatedAt.getTime(),
      archivedAt: prismaModel.archivedAt?.getTime(),
      deletedAt: prismaModel.deletedAt?.getTime(),
      lastMessageAt: prismaModel.lastMessageAt?.getTime(),
      metadata: prismaModel.metadata,
      version: prismaModel.version,
    };
  }
}
