import { Injectable, NotFoundException } from '@nestjs/common';
import { Conversation, Message, Run } from './conversation.types';
import { PrismaService } from '../prisma/prisma.service';
import * as crypto from 'crypto';
import { MessageRole, RunStatus } from '@prisma/client';

@Injectable()
export class ConversationService {
  constructor(private readonly prisma: PrismaService) {}

  async createConversation(workspaceId: string, body?: { title?: string; metadata?: Record<string, any> }): Promise<Conversation> {
    const id = crypto.randomUUID();
    const conv = await this.prisma.conversation.create({
      data: {
        id,
        title: body?.title || 'New Conversation',
        workspaceId,
        metadata: body?.metadata || {},
      }
    });
    return this.mapConversation(conv);
  }

  async getAllConversations(workspaceId: string): Promise<Conversation[]> {
    const convs = await this.prisma.conversation.findMany({ 
      where: { workspaceId },
      orderBy: { updatedAt: 'desc' } 
    });
    return convs.map(this.mapConversation);
  }

  async getConversation(workspaceId: string, id: string): Promise<Conversation> {
    let conv = await this.prisma.conversation.findUnique({ where: { id } });
    if (conv && conv.workspaceId !== workspaceId) {
      throw new NotFoundException('Conversation not found in your workspace');
    }
    if (!conv) {
      conv = await this.prisma.conversation.create({
        data: { id, title: 'Recovered Conversation', workspaceId }
      });
    }
    return this.mapConversation(conv);
  }

  async updateConversation(workspaceId: string, id: string, updates: { title?: string }): Promise<Conversation> {
    await this.getConversation(workspaceId, id);
    const conv = await this.prisma.conversation.update({
      where: { id },
      data: { title: updates.title, version: { increment: 1 } },
    });
    return this.mapConversation(conv);
  }

  async getMessages(workspaceId: string, conversationId: string): Promise<Message[]> {
    await this.getConversation(workspaceId, conversationId);
    const msgs = await this.prisma.message.findMany({
      where: { conversationId },
      include: { parts: { orderBy: { order: 'asc' } } },
      orderBy: { createdAt: 'asc' },
    });
    return msgs.map(this.mapMessage);
  }

  async appendMessage(workspaceId: string, conversationId: string, message: Message): Promise<Message> {
    await this.getConversation(workspaceId, conversationId);
    
    const msgId = message.id || crypto.randomUUID();
    const msg = await this.prisma.message.create({
      data: {
        id: msgId,
        conversationId,
        role: message.role as MessageRole,
        metadata: message.metadata || {},
        parts: {
          create: message.parts.map((p) => ({
            id: p.id,
            type: p.type,
            status: p.status,
            order: p.order,
            content: p.content,
            metadata: p.metadata || {},
            toolCallId: p.toolCallId,
            createdAt: p.createdAt ? new Date(p.createdAt) : undefined,
          })),
        },
      },
      include: { parts: true },
    });
    
    await this.prisma.conversation.update({
      where: { id: conversationId },
      data: { 
        version: { increment: 1 },
        lastMessageAt: msg.createdAt,
      },
    });
    
    return this.mapMessage(msg);
  }

  async clearMessages(workspaceId: string, conversationId: string): Promise<void> {
    await this.getConversation(workspaceId, conversationId);
    await this.prisma.message.deleteMany({ where: { conversationId } });
  }

  async deleteConversation(workspaceId: string, id: string): Promise<void> {
    await this.getConversation(workspaceId, id);
    await this.prisma.conversation.delete({ where: { id } }).catch(() => {});
  }

  private mapConversation = (conv: any): Conversation => ({
    id: conv.id,
    title: conv.title || 'Untitled',
    summary: conv.summary,
    isAutoGenerated: conv.isAutoGenerated || false,
    createdAt: conv.createdAt.getTime(),
    updatedAt: conv.updatedAt.getTime(),
    archivedAt: conv.archivedAt?.getTime(),
    deletedAt: conv.deletedAt?.getTime(),
    lastMessageAt: conv.lastMessageAt?.getTime(),
    metadata: conv.metadata,
    version: conv.version,
  });

  private mapMessage = (msg: any): Message => {
    return {
      id: msg.id,
      role: msg.role as any,
      createdAt: msg.createdAt.getTime(),
      metadata: msg.metadata || undefined,
      parts: (msg.parts || []).map((p: any) => ({
        id: p.id,
        type: p.type as any,
        status: p.status as any,
        order: p.order,
        content: p.content,
        metadata: p.metadata || undefined,
        toolCallId: p.toolCallId || undefined,
        createdAt: p.createdAt.getTime(),
      })),
    };
  };

  createRun(conversationId: string, metadata?: Record<string, any>): Run {
    throw new Error('Use ExecutionTrackerService for Runs');
  }

  getRun(runId: string): Run {
    throw new Error('Use ExecutionTrackerService for Runs');
  }

  updateRunStatus(runId: string, status: RunStatus, terminationReason?: string): Run {
    throw new Error('Use ExecutionTrackerService for Runs');
  }
}
