import { MessageRole, MessagePartType, MessagePartStatus, RunStatus } from '@prisma/client';

export interface MessagePart {
  id: string;
  type: MessagePartType;
  status: MessagePartStatus;
  order: number;
  content: any; // JSON
  metadata?: any;
  toolCallId?: string;
  createdAt: number;
}

export interface Message {
  id: string;
  role: MessageRole;
  createdAt: number;
  metadata?: Record<string, any>;
  parts: MessagePart[];
}

export interface Run {
  id: string;
  conversationId: string;
  status: RunStatus;
  createdAt: number;
  endedAt?: number;
  terminationReason?: string;
  metadata?: Record<string, any>;
  version: number;
}

export interface Conversation {
  id: string;
  title: string;
  summary?: string;
  isAutoGenerated: boolean;
  createdAt: number;
  updatedAt: number;
  archivedAt?: number;
  deletedAt?: number;
  lastMessageAt?: number;
  metadata?: Record<string, any>;
  version: number;
}
